config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'flights#index'
  resources :flights
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :departure_airport, class_name: 'Flight'
  has_many :arriving_flights, foreign_key: :arrival_airport, class_name: 'Flight'

  validates :code, :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers, dependent: :destroy
  belongs_to :flight
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :bookings
  has_many :passengers, through: :bookings

  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'

  validates :departure_time, :duration, presence: true

  def self.user_search(query_params)
    where(departure_airport_id: query_params[:departure_airport_id], arrival_airport_id: query_params[:arrival_airport_id])
    #,departure_date: query_params[:departure_date]
  end

  def departure_date_formatted
    departure_date.strftime("%B %d, %Y")
  end

  def departure_time_formatted
    departure_time.strftime("%l:%M %P")
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    @num_of_passengers = params[:num_of_passengers]
    @booking.passengers.build
  end

  def create
    @flight = Flight.find(booking_params[:flight_id])
    @booking = @flight.bookings.build(booking_params)

    if @booking.save
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all
    @flights = Flight.all
    @searched_flights = Flight.user_search(query_params)
    @num_of_passengers = query_params[:passengers]
    @departure_airport = Airport.where(id: query_params[:departure_airport_id])
    @arrival_airport = Airport.where(id: query_params[:arrival_airport_id])
    @departure_date = query_params[:departure_date]
  end

  private
  def query_params
    params.permit(:departure_airport_id, :arrival_airport_id, :passengers, :departure_time, :departure_date, :commit, :authenticity_token, :flight_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<%= form_with model: @booking do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being created:</h2>
      <ul>
        <% @booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <div>
        <h4>
          <%= "#{@flight.departure_airport.name} (#{@flight.departure_airport.code}) to
              #{@flight.arrival_airport.name} (#{@flight.arrival_airport.code})" %>
        </h4>
      </div>
      <div>
        <%= "Departure: #{@flight.departure_date_formatted} - #{@flight.departure_time_formatted}" %>
      </div>
      <div>
        <%= "Duration: #{@flight.duration.to_i} hours" %>
      </div>
      <div>
        <%= "Flight Number: #{@flight.id}" %>
      </div>
    </div>

    <hr>
    <% (1..@num_of_passengers.to_i).each do |passenger_number| %>
      <div>
        <% if @num_of_passengers.to_i > 1 %>
          <h4><%= "Passenger #{passenger_number} Information" %></h4>
        <% else %>
          <h4><%= "Passenger Information" %></h4>
        <% end %>

        <%= form.fields_for :passengers do |sub_form|  %>
          <%= form.hidden_field :flight_id, value: @flight.id %>
          <div>
            <%= sub_form.label :name %>
            <%= sub_form.text_field :name%>
          </div>
          <div>
            <%= sub_form.label :email %>
            <%= sub_form.email_field :email%>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= form.submit "Purchase Flight"%>
  </div>
<% end %>

app/views/bookings/show.html.erb
<div>
    <h3>Your flight has been booked!</h3>
    <div>
        <h4>
            <%= "#{@booking.flight.departure_airport.name} (#{@booking.flight.departure_airport.code}) to
            #{@booking.flight.arrival_airport.name} (#{@booking.flight.arrival_airport.code})" %>
        </h4>
    </div>

    <div>
        <%= "Departure: #{@booking.flight.departure_date_formatted}"%>
        <%#  - #{@booking.departure_time_formatted} %>
    </div>

    <div>
        <%= "Duration: #{@booking.flight.duration.to_i}"%>
    </div>

    <div>
        <%= "Flight number: #{@booking.flight.id}"%>
    </div>
</div>

<% @booking.passengers.each_with_index do |passenger, passenger_number| %>
    <div>
        <% if @booking.passengers.count > 1 %>
            <h4><%= "Passenger #{passenger_number + 1} Infromation"%></h4>
        <% else %>
            <h4><%= "Passenger Infromation" %></h4>
        <% end %>

        <hr>

        <h5><%= "Name" %></h5>
        <div><%= passenger.name.titleize %></div>

        <h5><%= "Email" %></h5>
        <div><%= passenger.email %></div>
    </div>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_with(model: @flight, url: flights_path, method: "get") do |form|%>
    <% @days = Flight.all.pluck(:departure_date).uniq.sort %>

    <div>
        <h2>Book a one-way flight</h2>

        <div>
            <h4>Departure</h4>
            <%= select_tag 'departure_airport_id', options_from_collection_for_select(@airports, 'id', 'name'), include_blank: 'From', class: 'form_select'%>
        </div>

        <div>
            <h4>Arrival</h4>
            <%= select_tag 'arrival_airport_id', options_from_collection_for_select(@airports, 'id', 'name'), include_blank: 'To', class: 'form_select'%>
        </div>

        <div>
            <h4>Date</h4>
            <%= select_tag 'departure_date', options_for_select(@days), include_blank: 'Departing', class: 'form_select'%>
        </div>

        <div>
            <h4>Passengers</h4>
            <%= select_tag 'passengers', options_for_select(1..4), class: 'form_select'%>
        </div>
    </div>

    <%= form.submit 'Search' %>    
<% end%>

app/views/flights/_selection_form.html.erb
<% unless @departure_airport.blank? && @arrival_airport.blank? && @departure_date.blank? %>
  <% if @searched_flights.present? %>
    <%= form_with(model: @flight, url: new_booking_path, method: "get") do |form| %> 
      <%= form.hidden_field :num_of_passengers, value: @num_of_passengers %>

      <div >
        <h4>
          <%= "Search results" %>
        </h4>
        <h5>
          <%= "#{pluralize(@searched_flights.count, "flight")} available
               for #{@searched_flights.first.departure_date_formatted}" %>
        </h5>

        <% @searched_flights.each do |flight| %>
          <div>
            <div>
              <%= form.radio_button :flight_id, flight.id%>
            </div>

            <div>
                  <%= "#{flight.departure_airport.name}
                       (#{flight.departure_airport.code}) to
                       #{flight.arrival_airport.name}
                       (#{flight.arrival_airport.code})" %>
            </div>
            <div>
                  <%= "Departure: #{flight.departure_time_formatted}" %>
            </div>
            <div>
                  <%= "Duration: #{flight.duration.to_i} hours" %>
            </div>
          </div>
        <% end %>

        <%= form.submit "Book"%>
      </div>
    <% end %>
  <% else %>
    <div>
      <h4>No flights found, please try again.</h4>
    </div>
  <% end %>
<% end %>

        

app/views/flights/index.html.erb
<div>
    <%= render "search_form" %>

    <%= render "selection_form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>